services:
  - type: web
    name: constant-lists-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false  # You'll set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false  # You'll set this manually in Render dashboard
      - key: BCRYPT_ROUNDS
        value: 10